<?php

namespace Database\Seeders;

use App\Models\Medication;
use Illuminate\Database\Seeder;

class MedicationSeeder extends Seeder
{
    public function run(): void
    {
        $medications = [
            // ─── WEIGHT LOSS (GLP-1) ─────────────────────────────────────────
            [
                'name' => 'Semaglutide',
                'generic_name' => 'Semaglutide',
                'brand_name' => 'Ozempic',
                'form' => 'injection',
                'strength' => '0.25mg/0.5mg/1mg',
                'schedule' => 'S4',
                'nappi_code' => '720631001',
                'category' => 'weight-loss',
                'price_cents' => 121000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'GLP-1 receptor agonist for weight management. Reduces appetite and improves blood sugar control.',
                'dosage_instructions' => 'Inject once weekly subcutaneously. Start at 0.25mg for 4 weeks, then increase as directed.',
                'manufacturer' => 'Novo Nordisk',
            ],
            [
                'name' => 'Semaglutide (Wegovy)',
                'generic_name' => 'Semaglutide',
                'brand_name' => 'Wegovy',
                'form' => 'injection',
                'strength' => '2.4mg',
                'schedule' => 'S4',
                'nappi_code' => '720631002',
                'category' => 'weight-loss',
                'price_cents' => 285000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Higher-dose semaglutide specifically approved for chronic weight management.',
                'dosage_instructions' => 'Inject once weekly. Dose escalation over 16-20 weeks to maintenance dose of 2.4mg.',
                'manufacturer' => 'Novo Nordisk',
            ],
            [
                'name' => 'Liraglutide',
                'generic_name' => 'Liraglutide',
                'brand_name' => 'Saxenda',
                'form' => 'injection',
                'strength' => '3mg',
                'schedule' => 'S4',
                'nappi_code' => '718754001',
                'category' => 'weight-loss',
                'price_cents' => 395000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'GLP-1 receptor agonist for weight loss. Daily injection that reduces hunger.',
                'dosage_instructions' => 'Inject once daily subcutaneously. Start at 0.6mg, increase by 0.6mg weekly to 3mg.',
                'manufacturer' => 'Novo Nordisk',
            ],

            // ─── ERECTILE DYSFUNCTION ────────────────────────────────────────
            [
                'name' => 'Sildenafil',
                'generic_name' => 'Sildenafil Citrate',
                'brand_name' => 'Viagra',
                'form' => 'tablet',
                'strength' => '50mg',
                'schedule' => 'S4',
                'nappi_code' => '706127001',
                'category' => 'mens-health',
                'price_cents' => 8500,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'PDE5 inhibitor for erectile dysfunction. Take on-demand before sexual activity.',
                'dosage_instructions' => 'Take 1 tablet 30-60 minutes before sexual activity. Do not exceed 1 tablet per day.',
                'manufacturer' => 'Pfizer',
            ],
            [
                'name' => 'Sildenafil 100mg',
                'generic_name' => 'Sildenafil Citrate',
                'brand_name' => 'Viagra',
                'form' => 'tablet',
                'strength' => '100mg',
                'schedule' => 'S4',
                'nappi_code' => '706127002',
                'category' => 'mens-health',
                'price_cents' => 12000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Higher dose PDE5 inhibitor for erectile dysfunction.',
                'dosage_instructions' => 'Take 1 tablet 30-60 minutes before sexual activity. Do not exceed 1 tablet per day.',
                'manufacturer' => 'Pfizer',
            ],
            [
                'name' => 'Tadalafil',
                'generic_name' => 'Tadalafil',
                'brand_name' => 'Cialis',
                'form' => 'tablet',
                'strength' => '20mg',
                'schedule' => 'S4',
                'nappi_code' => '708693001',
                'category' => 'mens-health',
                'price_cents' => 14000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Long-acting PDE5 inhibitor. Lasts up to 36 hours.',
                'dosage_instructions' => 'Take 1 tablet at least 30 minutes before sexual activity. Effects last up to 36 hours.',
                'manufacturer' => 'Eli Lilly',
            ],
            [
                'name' => 'Tadalafil Daily',
                'generic_name' => 'Tadalafil',
                'brand_name' => 'Cialis Daily',
                'form' => 'tablet',
                'strength' => '5mg',
                'schedule' => 'S4',
                'nappi_code' => '708693002',
                'category' => 'mens-health',
                'price_cents' => 22000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Daily low-dose tadalafil for continuous readiness.',
                'dosage_instructions' => 'Take 1 tablet daily at the same time, regardless of sexual activity.',
                'manufacturer' => 'Eli Lilly',
            ],

            // ─── HAIR LOSS ───────────────────────────────────────────────────
            [
                'name' => 'Finasteride',
                'generic_name' => 'Finasteride',
                'brand_name' => 'Propecia',
                'form' => 'tablet',
                'strength' => '1mg',
                'schedule' => 'S4',
                'nappi_code' => '703408001',
                'category' => 'general-health',
                'price_cents' => 18000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'DHT blocker that stops hair loss and promotes regrowth in male-pattern baldness.',
                'dosage_instructions' => 'Take 1 tablet daily. Results visible after 3-6 months of consistent use.',
                'manufacturer' => 'MSD',
            ],
            [
                'name' => 'Minoxidil Topical',
                'generic_name' => 'Minoxidil',
                'brand_name' => 'Regaine',
                'form' => 'liquid',
                'strength' => '5%',
                'schedule' => 'S2',
                'nappi_code' => '701234001',
                'category' => 'general-health',
                'price_cents' => 25000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Topical solution that stimulates hair follicles and promotes regrowth.',
                'dosage_instructions' => 'Apply 1ml to affected scalp area twice daily. Allow to dry before styling.',
                'manufacturer' => 'Johnson & Johnson',
            ],

            // ─── SKINCARE ────────────────────────────────────────────────────
            [
                'name' => 'Tretinoin Cream',
                'generic_name' => 'Tretinoin',
                'brand_name' => 'Retin-A',
                'form' => 'cream',
                'strength' => '0.025%',
                'schedule' => 'S4',
                'nappi_code' => '700891001',
                'category' => 'skincare',
                'price_cents' => 15000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Prescription retinoid for acne and anti-aging. Promotes cell turnover.',
                'dosage_instructions' => 'Apply a pea-sized amount to clean, dry face at night. Use sunscreen daily.',
                'manufacturer' => 'Various',
            ],
            [
                'name' => 'Adapalene Gel',
                'generic_name' => 'Adapalene',
                'brand_name' => 'Differin',
                'form' => 'gel',
                'strength' => '0.1%',
                'schedule' => 'S4',
                'nappi_code' => '712456001',
                'category' => 'skincare',
                'price_cents' => 12000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Third-generation retinoid for mild to moderate acne.',
                'dosage_instructions' => 'Apply thin layer to affected areas once daily at bedtime on clean, dry skin.',
                'manufacturer' => 'Galderma',
            ],
            [
                'name' => 'Doxycycline',
                'generic_name' => 'Doxycycline',
                'brand_name' => 'Doxytet',
                'form' => 'capsule',
                'strength' => '100mg',
                'schedule' => 'S4',
                'nappi_code' => '700234001',
                'category' => 'skincare',
                'price_cents' => 8500,
                'repeat_cycle_days' => 30,
                'is_subscription' => false,
                'description' => 'Oral antibiotic for moderate-to-severe inflammatory acne.',
                'dosage_instructions' => 'Take 1 capsule daily with food and a full glass of water. Avoid lying down for 30 minutes.',
                'manufacturer' => 'Various',
            ],

            // ─── CONTRACEPTION ───────────────────────────────────────────────
            [
                'name' => 'Yasmin',
                'generic_name' => 'Drospirenone/Ethinylestradiol',
                'brand_name' => 'Yasmin',
                'form' => 'tablet',
                'strength' => '3mg/0.03mg',
                'schedule' => 'S4',
                'nappi_code' => '709123001',
                'category' => 'womens-health',
                'price_cents' => 18000,
                'repeat_cycle_days' => 28,
                'is_subscription' => true,
                'description' => 'Combined oral contraceptive pill. Also helps with acne and PMS.',
                'dosage_instructions' => 'Take 1 tablet daily at the same time for 21 days, then 7 days break.',
                'manufacturer' => 'Bayer',
            ],
            [
                'name' => 'Noriday',
                'generic_name' => 'Norethisterone',
                'brand_name' => 'Noriday',
                'form' => 'tablet',
                'strength' => '0.35mg',
                'schedule' => 'S4',
                'nappi_code' => '700567001',
                'category' => 'womens-health',
                'price_cents' => 9500,
                'repeat_cycle_days' => 28,
                'is_subscription' => true,
                'description' => 'Progestogen-only pill (mini pill). Suitable for women who cannot take oestrogen.',
                'dosage_instructions' => 'Take 1 tablet daily at the same time, no break between packs.',
                'manufacturer' => 'Pfizer',
            ],

            // ─── GENERAL / CHRONIC ───────────────────────────────────────────
            [
                'name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'brand_name' => 'Losec',
                'form' => 'capsule',
                'strength' => '20mg',
                'schedule' => 'S4',
                'nappi_code' => '700456001',
                'category' => 'general-health',
                'price_cents' => 6500,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Proton pump inhibitor for acid reflux, heartburn, and GORD.',
                'dosage_instructions' => 'Take 1 capsule daily before breakfast on an empty stomach.',
                'manufacturer' => 'AstraZeneca',
            ],
            [
                'name' => 'Pantoprazole',
                'generic_name' => 'Pantoprazole',
                'brand_name' => 'Pantoloc',
                'form' => 'tablet',
                'strength' => '40mg',
                'schedule' => 'S4',
                'nappi_code' => '710345001',
                'category' => 'general-health',
                'price_cents' => 8000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'PPI for acid reflux and gastric ulcers. Longer acting than omeprazole.',
                'dosage_instructions' => 'Take 1 tablet daily in the morning before food.',
                'manufacturer' => 'Takeda',
            ],
            [
                'name' => 'Sertraline',
                'generic_name' => 'Sertraline',
                'brand_name' => 'Zoloft',
                'form' => 'tablet',
                'strength' => '50mg',
                'schedule' => 'S5',
                'nappi_code' => '702890001',
                'category' => 'general-health',
                'price_cents' => 11000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'SSRI antidepressant for depression, anxiety, PTSD, and OCD.',
                'dosage_instructions' => 'Take 1 tablet daily in the morning or evening. Do not stop abruptly.',
                'manufacturer' => 'Pfizer',
            ],

            // ─── SEXUAL HEALTH ───────────────────────────────────────────────
            [
                'name' => 'Valaciclovir',
                'generic_name' => 'Valaciclovir',
                'brand_name' => 'Valtrex',
                'form' => 'tablet',
                'strength' => '500mg',
                'schedule' => 'S4',
                'nappi_code' => '706789001',
                'category' => 'sexual-health',
                'price_cents' => 32000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'Antiviral for genital herpes — treats outbreaks and suppresses recurrence.',
                'dosage_instructions' => 'Episodic: 500mg twice daily for 3-5 days. Suppressive: 500mg once daily.',
                'manufacturer' => 'GSK',
            ],
            [
                'name' => 'Azithromycin',
                'generic_name' => 'Azithromycin',
                'brand_name' => 'Zithromax',
                'form' => 'tablet',
                'strength' => '500mg',
                'schedule' => 'S4',
                'nappi_code' => '704567001',
                'category' => 'sexual-health',
                'price_cents' => 7500,
                'repeat_cycle_days' => null,
                'is_subscription' => false,
                'description' => 'Antibiotic for chlamydia and other STIs. Single-dose treatment.',
                'dosage_instructions' => 'Take 2 tablets (1g) as a single dose. Can be taken with or without food.',
                'manufacturer' => 'Pfizer',
            ],
            [
                'name' => 'Dapoxetine',
                'generic_name' => 'Dapoxetine',
                'brand_name' => 'Priligy',
                'form' => 'tablet',
                'strength' => '30mg',
                'schedule' => 'S4',
                'nappi_code' => '715678001',
                'category' => 'mens-health',
                'price_cents' => 28000,
                'repeat_cycle_days' => 30,
                'is_subscription' => true,
                'description' => 'SSRI for premature ejaculation. Take on-demand before sexual activity.',
                'dosage_instructions' => 'Take 1 tablet 1-3 hours before sexual activity. Do not exceed 1 tablet in 24 hours.',
                'manufacturer' => 'Menarini',
            ],

            // ─── UTI / THRUSH ────────────────────────────────────────────────
            [
                'name' => 'Nitrofurantoin',
                'generic_name' => 'Nitrofurantoin',
                'brand_name' => 'Macrodantin',
                'form' => 'capsule',
                'strength' => '100mg',
                'schedule' => 'S4',
                'nappi_code' => '700123001',
                'category' => 'general-health',
                'price_cents' => 9500,
                'repeat_cycle_days' => null,
                'is_subscription' => false,
                'description' => 'Antibiotic specifically for urinary tract infections.',
                'dosage_instructions' => 'Take 1 capsule twice daily with food for 5 days. Complete the full course.',
                'manufacturer' => 'Various',
            ],
            [
                'name' => 'Fluconazole',
                'generic_name' => 'Fluconazole',
                'brand_name' => 'Diflucan',
                'form' => 'capsule',
                'strength' => '150mg',
                'schedule' => 'S4',
                'nappi_code' => '703456001',
                'category' => 'general-health',
                'price_cents' => 5500,
                'repeat_cycle_days' => null,
                'is_subscription' => false,
                'description' => 'Antifungal for vaginal and oral thrush. Single-dose treatment.',
                'dosage_instructions' => 'Take 1 capsule as a single dose. Symptoms should improve within 1-3 days.',
                'manufacturer' => 'Pfizer',
            ],
        ];

        foreach ($medications as $med) {
            Medication::updateOrCreate(
                ['nappi_code' => $med['nappi_code']],
                array_merge($med, ['is_active' => true])
            );
        }
    }
}
